--- #YAML:1.0
name:               Data-CTable
version:            1.03_02
abstract:           Read, write, manipulate tabular data
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    FindBin:     0
    Test::More:  0
resources:
    bugtracker:  https://rt.cpan.org/Public/Dist/Display.html?Name=Data-CTable
    homepage:    http://christhorman.com/projects/perl/Data-CTable/
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/jhannah/data-ctable
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
